# Generated by Django 5.0.7 on 2024-07-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_img',
            field=models.ImageField(default=None, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='product',
            name='second_img',
            field=models.ImageField(default=None, upload_to='products'),
        ),
    ]
